name: Pull Request Recap

on:
  pull_request:
    types: [opened]

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        uses: flowwer-dev/recap@dev
        with:
          openai-apikey: ${{ secrets.OPENAI_APIKEY }}
