name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    - name: Pull Request Stats
      uses: flowwer-dev/pull-request-stats@v2.9.0

