name: Pull Request Stats

on:
  pull_request:
    types: [merged]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 7
          charts: true
          limit: 15
          sort-by: 'REVIEWS'
          disable-links: false
          publish-as: 'DESCRIPTION'
          # telemetry: false
          # slack-channel: '#demo-pr-stats-integration'
          # slack-webhook: 'https://hooks.slack.com/services/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'
